const TIMEZONES = [
  { tz: "Pacific/Midway",         label: "Midway Island",                          offset: "UTC−11" },
  { tz: "Pacific/Niue",           label: "Niue",                                   offset: "UTC−11" },
  { tz: "Pacific/Honolulu",       label: "Honolulu, Hawaii, USA",                  offset: "UTC−10" },
  { tz: "Pacific/Tahiti",         label: "Tahiti, French Polynesia",               offset: "UTC−10" },
  { tz: "Pacific/Marquesas",      label: "Marquesas Islands",                      offset: "UTC−9:30" },
  { tz: "America/Anchorage",      label: "Anchorage, Alaska, USA",                 offset: "UTC−9" },
  { tz: "America/Juneau",         label: "Juneau, Alaska, USA",                    offset: "UTC−9" },
  { tz: "America/Los_Angeles",    label: "Los Angeles, California, USA",           offset: "UTC−8" },
  { tz: "America/Vancouver",      label: "Vancouver, British Columbia, Canada",    offset: "UTC−8" },
  { tz: "America/Seattle",        label: "Seattle, Washington, USA",               offset: "UTC−8" },
  { tz: "America/San_Francisco",  label: "San Francisco, California, USA",         offset: "UTC−8" },
  { tz: "America/Las_Vegas",      label: "Las Vegas, Nevada, USA",                 offset: "UTC−8" },
  { tz: "America/Tijuana",        label: "Tijuana, Mexico",                        offset: "UTC−8" },
  { tz: "America/Denver",         label: "Denver, Colorado, USA",                  offset: "UTC−7" },
  { tz: "America/Calgary",        label: "Calgary, Alberta, Canada",               offset: "UTC−7" },
  { tz: "America/Edmonton",       label: "Edmonton, Alberta, Canada",              offset: "UTC−7" },
  { tz: "America/Phoenix",        label: "Phoenix, Arizona, USA",                  offset: "UTC−7" },
  { tz: "America/Chihuahua",      label: "Chihuahua, Mexico",                      offset: "UTC−7" },
  { tz: "America/Chicago",        label: "Chicago, Illinois, USA",                 offset: "UTC−6" },
  { tz: "America/Winnipeg",       label: "Winnipeg, Manitoba, Canada",             offset: "UTC−6" },
  { tz: "America/Dallas",         label: "Dallas, Texas, USA",                     offset: "UTC−6" },
  { tz: "America/Mexico_City",    label: "Mexico City, Mexico",                    offset: "UTC−6" },
  { tz: "America/Guatemala",      label: "Guatemala City, Guatemala",              offset: "UTC−6" },
  { tz: "America/Costa_Rica",     label: "San José, Costa Rica",                   offset: "UTC−6" },
  { tz: "America/New_York",       label: "New York, USA",                          offset: "UTC−5" },
  { tz: "America/Toronto",        label: "Toronto, Ontario, Canada",               offset: "UTC−5" },
  { tz: "America/Montreal",       label: "Montreal, Quebec, Canada",               offset: "UTC−5" },
  { tz: "America/Miami",          label: "Miami, Florida, USA",                    offset: "UTC−5" },
  { tz: "America/Boston",         label: "Boston, Massachusetts, USA",             offset: "UTC−5" },
  { tz: "America/Atlanta",        label: "Atlanta, Georgia, USA",                  offset: "UTC−5" },
  { tz: "America/Detroit",        label: "Detroit, Michigan, USA",                 offset: "UTC−5" },
  { tz: "America/Lima",           label: "Lima, Peru",                             offset: "UTC−5" },
  { tz: "America/Bogota",         label: "Bogotá, Colombia",                       offset: "UTC−5" },
  { tz: "America/Halifax",        label: "Halifax, Nova Scotia, Canada",           offset: "UTC−4" },
  { tz: "America/La_Paz",         label: "La Paz, Bolivia",                        offset: "UTC−4" },
  { tz: "America/Caracas",        label: "Caracas, Venezuela",                     offset: "UTC−4" },
  { tz: "America/Santiago",       label: "Santiago, Chile",                        offset: "UTC−4" },
  { tz: "America/St_Johns",       label: "St. John's, Newfoundland, Canada",       offset: "UTC−3:30" },
  { tz: "America/Sao_Paulo",      label: "São Paulo, Brazil",                      offset: "UTC−3" },
  { tz: "America/Rio_de_Janeiro", label: "Rio de Janeiro, Brazil",                 offset: "UTC−3" },
  { tz: "America/Argentina/Buenos_Aires", label: "Buenos Aires, Argentina",        offset: "UTC−3" },
  { tz: "America/Montevideo",     label: "Montevideo, Uruguay",                    offset: "UTC−3" },
  { tz: "Atlantic/South_Georgia", label: "South Georgia Island",                   offset: "UTC−2" },
  { tz: "Atlantic/Cape_Verde",    label: "Cape Verde",                             offset: "UTC−1" },
  { tz: "Atlantic/Azores",        label: "Azores, Portugal",                       offset: "UTC−1" },
  { tz: "Europe/London",          label: "London, United Kingdom",                 offset: "UTC+0" },
  { tz: "Europe/Dublin",          label: "Dublin, Ireland",                        offset: "UTC+0" },
  { tz: "Europe/Lisbon",          label: "Lisbon, Portugal",                       offset: "UTC+0" },
  { tz: "Africa/Casablanca",      label: "Casablanca, Morocco",                    offset: "UTC+0" },
  { tz: "Africa/Accra",           label: "Accra, Ghana",                           offset: "UTC+0" },
  { tz: "Europe/Paris",           label: "Paris, France",                          offset: "UTC+1" },
  { tz: "Europe/Berlin",          label: "Berlin, Germany",                        offset: "UTC+1" },
  { tz: "Europe/Rome",            label: "Rome, Italy",                            offset: "UTC+1" },
  { tz: "Europe/Madrid",          label: "Madrid, Spain",                          offset: "UTC+1" },
  { tz: "Europe/Amsterdam",       label: "Amsterdam, Netherlands",                 offset: "UTC+1" },
  { tz: "Europe/Brussels",        label: "Brussels, Belgium",                      offset: "UTC+1" },
  { tz: "Europe/Vienna",          label: "Vienna, Austria",                        offset: "UTC+1" },
  { tz: "Europe/Zurich",          label: "Zurich, Switzerland",                    offset: "UTC+1" },
  { tz: "Europe/Prague",          label: "Prague, Czech Republic",                 offset: "UTC+1" },
  { tz: "Europe/Warsaw",          label: "Warsaw, Poland",                         offset: "UTC+1" },
  { tz: "Europe/Stockholm",       label: "Stockholm, Sweden",                      offset: "UTC+1" },
  { tz: "Europe/Oslo",            label: "Oslo, Norway",                           offset: "UTC+1" },
  { tz: "Europe/Copenhagen",      label: "Copenhagen, Denmark",                    offset: "UTC+1" },
  { tz: "Africa/Lagos",           label: "Lagos, Nigeria",                         offset: "UTC+1" },
  { tz: "Africa/Tunis",           label: "Tunis, Tunisia",                         offset: "UTC+1" },
  { tz: "Europe/Athens",          label: "Athens, Greece",                         offset: "UTC+2" },
  { tz: "Europe/Helsinki",        label: "Helsinki, Finland",                      offset: "UTC+2" },
  { tz: "Europe/Kyiv",            label: "Kyiv, Ukraine",                          offset: "UTC+2" },
  { tz: "Europe/Bucharest",       label: "Bucharest, Romania",                     offset: "UTC+2" },
  { tz: "Europe/Sofia",           label: "Sofia, Bulgaria",                        offset: "UTC+2" },
  { tz: "Asia/Jerusalem",         label: "Jerusalem / Tel Aviv, Israel",           offset: "UTC+2" },
  { tz: "Asia/Beirut",            label: "Beirut, Lebanon",                        offset: "UTC+2" },
  { tz: "Asia/Amman",             label: "Amman, Jordan",                          offset: "UTC+2" },
  { tz: "Africa/Cairo",           label: "Cairo, Egypt",                           offset: "UTC+2" },
  { tz: "Africa/Johannesburg",    label: "Johannesburg, South Africa",             offset: "UTC+2" },
  { tz: "Africa/Harare",          label: "Harare, Zimbabwe",                       offset: "UTC+2" },
  { tz: "Europe/Moscow",          label: "Moscow, Russia",                         offset: "UTC+3" },
  { tz: "Europe/Istanbul",        label: "Istanbul, Turkey",                       offset: "UTC+3" },
  { tz: "Asia/Riyadh",            label: "Riyadh, Saudi Arabia",                   offset: "UTC+3" },
  { tz: "Asia/Kuwait",            label: "Kuwait City, Kuwait",                    offset: "UTC+3" },
  { tz: "Asia/Baghdad",           label: "Baghdad, Iraq",                          offset: "UTC+3" },
  { tz: "Asia/Qatar",             label: "Doha, Qatar",                            offset: "UTC+3" },
  { tz: "Africa/Nairobi",         label: "Nairobi, Kenya",                         offset: "UTC+3" },
  { tz: "Africa/Addis_Ababa",     label: "Addis Ababa, Ethiopia",                  offset: "UTC+3" },
  { tz: "Asia/Tehran",            label: "Tehran, Iran",                           offset: "UTC+3:30" },
  { tz: "Asia/Dubai",             label: "Dubai, UAE",                             offset: "UTC+4" },
  { tz: "Asia/Abu_Dhabi",         label: "Abu Dhabi, UAE",                         offset: "UTC+4" },
  { tz: "Asia/Baku",              label: "Baku, Azerbaijan",                       offset: "UTC+4" },
  { tz: "Asia/Tbilisi",           label: "Tbilisi, Georgia",                       offset: "UTC+4" },
  { tz: "Indian/Mauritius",       label: "Mauritius",                              offset: "UTC+4" },
  { tz: "Asia/Kabul",             label: "Kabul, Afghanistan",                     offset: "UTC+4:30" },
  { tz: "Asia/Karachi",           label: "Karachi, Pakistan",                      offset: "UTC+5" },
  { tz: "Asia/Tashkent",          label: "Tashkent, Uzbekistan",                   offset: "UTC+5" },
  { tz: "Asia/Yekaterinburg",     label: "Yekaterinburg, Russia",                  offset: "UTC+5" },
  { tz: "Asia/Kolkata",           label: "Mumbai / Delhi / Kolkata, India",        offset: "UTC+5:30" },
  { tz: "Asia/Colombo",           label: "Colombo, Sri Lanka",                     offset: "UTC+5:30" },
  { tz: "Asia/Kathmandu",         label: "Kathmandu, Nepal",                       offset: "UTC+5:45" },
  { tz: "Asia/Dhaka",             label: "Dhaka, Bangladesh",                      offset: "UTC+6" },
  { tz: "Asia/Almaty",            label: "Almaty, Kazakhstan",                     offset: "UTC+6" },
  { tz: "Asia/Rangoon",           label: "Yangon, Myanmar",                        offset: "UTC+6:30" },
  { tz: "Asia/Bangkok",           label: "Bangkok, Thailand",                      offset: "UTC+7" },
  { tz: "Asia/Jakarta",           label: "Jakarta, Indonesia",                     offset: "UTC+7" },
  { tz: "Asia/Ho_Chi_Minh",       label: "Ho Chi Minh City, Vietnam",              offset: "UTC+7" },
  { tz: "Asia/Phnom_Penh",        label: "Phnom Penh, Cambodia",                   offset: "UTC+7" },
  { tz: "Asia/Novosibirsk",       label: "Novosibirsk, Russia",                    offset: "UTC+7" },
  { tz: "Asia/Singapore",         label: "Singapore",                              offset: "UTC+8" },
  { tz: "Asia/Kuala_Lumpur",      label: "Kuala Lumpur, Malaysia",                 offset: "UTC+8" },
  { tz: "Asia/Shanghai",          label: "Shanghai / Beijing, China",              offset: "UTC+8" },
  { tz: "Asia/Hong_Kong",         label: "Hong Kong",                              offset: "UTC+8" },
  { tz: "Asia/Taipei",            label: "Taipei, Taiwan",                         offset: "UTC+8" },
  { tz: "Asia/Manila",            label: "Manila, Philippines",                    offset: "UTC+8" },
  { tz: "Asia/Makassar",          label: "Makassar, Indonesia",                    offset: "UTC+8" },
  { tz: "Australia/Perth",        label: "Perth, Western Australia",               offset: "UTC+8" },
  { tz: "Asia/Seoul",             label: "Seoul, South Korea",                     offset: "UTC+9" },
  { tz: "Asia/Tokyo",             label: "Tokyo, Japan",                           offset: "UTC+9" },
  { tz: "Asia/Pyongyang",         label: "Pyongyang, North Korea",                 offset: "UTC+9" },
  { tz: "Australia/Darwin",       label: "Darwin, Northern Territory, Australia",  offset: "UTC+9:30" },
  { tz: "Australia/Adelaide",     label: "Adelaide, South Australia",              offset: "UTC+9:30" },
  { tz: "Australia/Sydney",       label: "Sydney, New South Wales, Australia",     offset: "UTC+10" },
  { tz: "Australia/Melbourne",    label: "Melbourne, Victoria, Australia",         offset: "UTC+10" },
  { tz: "Australia/Brisbane",     label: "Brisbane, Queensland, Australia",        offset: "UTC+10" },
  { tz: "Pacific/Port_Moresby",   label: "Port Moresby, Papua New Guinea",         offset: "UTC+10" },
  { tz: "Australia/Lord_Howe",    label: "Lord Howe Island, Australia",            offset: "UTC+10:30" },
  { tz: "Pacific/Noumea",         label: "Noumea, New Caledonia",                  offset: "UTC+11" },
  { tz: "Pacific/Auckland",       label: "Auckland / Wellington, New Zealand",     offset: "UTC+12" },
  { tz: "Pacific/Fiji",           label: "Suva, Fiji",                             offset: "UTC+12" },
  { tz: "Pacific/Chatham",        label: "Chatham Islands, New Zealand",           offset: "UTC+12:45" },
  { tz: "Pacific/Tongatapu",      label: "Nuku'alofa, Tonga",                      offset: "UTC+13" },
  { tz: "Pacific/Apia",           label: "Apia, Samoa",                            offset: "UTC+13" },
];
